name: Lint and docs

permissions: {}

on: [push, pull_request]

jobs:
  lint_and_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.10"
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qy libdw-dev libelf-dev
      - name: Install Python dependencies
        run: |
          python3 -m pip install --group extra
      - name: Install Package
        run: |
          python3 -m pip install -e .
      - name: Lint sources
        run: |
          make lint PYTHON=python3
      - name: Build docs
        run: |
          towncrier build --version 99.99 --name pystack --keep
          make docs

  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
