name: Lint and docs

permissions: {}

on: [push, pull_request]

jobs:
  lint_and_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.10"
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qy libdw-dev libelf-dev
      - name: Install Python dependencies
        run: |
          python3 -m pip install --group extra
      - name: Install Package
        run: |
          python3 -m pip install -e .
      - name: Lint sources
        run: |
          make lint PYTHON=python3
      - name: Build docs
        run: |
          towncrier build --version 99.99 --name pystack --keep
          make docs

  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
